---
clone:
  depth: 1
kind: pipeline
name: pipe
steps:
  - name: build
    image: atomxorg/arch-linux:kernel
    commands:
      - pacman -Sy && pacman -S git bc inetutils python2 zip dtc clang lld llvm --noconfirm
      - export CLANG_VERSION=clang-r458507
      - git clone https://github.com/arter97/arm32-gcc/ --depth=1 -j$(nproc --all)
      - git clone https://github.com/arter97/arm64-gcc/ --depth=1 -j$(nproc --all)
      - wget https://github.com/Kaz205/clang-releases/releases/download/$CLANG_VERSION/$CLANG_VERSION.tar.xz
      - tar -I xz -xf $CLANG_VERSION.tar.xz && mv $CLANG_VERSION google-clang
      - git clone https://github.com/Kaz205/AnyKernel3 -b renoir --depth=1
      - ./drone.sh
      - curl bashupload.com -T AnyKernel3/*.zip
      - curl -i -T AnyKernel3/*.zip https://oshi.at

