---
clone:
  depth: 1
kind: pipeline
name: pipe
steps:
  - name: build
    image: panchajanya1999/archlinux:latest
    commands:
      - pacman -Sy && pacman -S dtc --noconfirm
      - git clone https://github.com/arter97/arm32-gcc/ --depth=1 -j$(nproc --all)
      - git clone https://github.com/arter97/arm64-gcc/ --depth=1 -j$(nproc --all)
      - wget https://github.com/Kaz205/clang-releases/releases/download/clang-r450784/clang-r450784.tar.xz
      - tar -I xz -xf clang-r450784.tar.xz && mv clang-r450784 google-clang
      - git clone https://github.com/Kaz205/AnyKernel3 -b renoir --depth=1
      - ./drone.sh
      - curl bashupload.com -T AnyKernel3/*.zip
      - curl -i -T AnyKernel3/*.zip https://oshi.at

